sudo: false
language: python
python:
  - "3.4"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install pip setuptools wheel --upgrade
  - pip install -r requirements.txt
  - pip install coveralls
script:
    coverage run manage.py test
after_success:
  - coveralls
