language: python
python:
  - "3.4"
before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - pip install pip setuptools --upgrade
  - pip install -r requirements.txt
  - pip install coveralls
script:
    coverage run manage.py test
after_success:
  - coveralls
