sudo: false
language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.cache/pip
    - assets/js/tests/elm-stuff/build-artifacts
    - $HOME/.nvm/versions
install:
  - pip install pip setuptools wheel --upgrade
  - pip install -r test_requirements.txt
  - pip install coveralls
  - nvm install v6
  - npm install
script:
  - make test
#  - make elm-test
after_success:
  - coveralls
