sudo: false
language: python
python:
  - "3.4"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install pip setuptools wheel --upgrade
  - pip install -r test_requirements.txt
  - pip install coveralls
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 5.0.0
  - npm install -g elm elm-test
script:
  - make test
  - make elm-test
after_success:
  - coveralls
