language: python
python:
  - "3.4"
install:
  - pip install pip setuptools --upgrade
  - pip install -r requirements.txt
  - pip install coveralls
script:
    coverage run manage.py test
after_success:
  - coveralls
