sudo: false
language: python
python:
  - "3.4"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install pip setuptools wheel --upgrade
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install -g elm elm-test
script:
  - make coverage
  - make elm-test
after_success:
  - coveralls
