---
- hosts: web
  vars:
    temp_path: '{{ ansible_env.HOME }}/tmp'
    project_path: '{{ ansible_env.HOME }}/variablestars.net'
    virtualenv_path: '{{ ansible_env.HOME }}/.virtualenvs/variablestars'
    node_version: v12.16.2
  environment:
    TMPDIR: '{{ temp_path }}'
    TMP: '{{ temp_path }}'
  tasks:
    #- name: build production assets
    #  local_action:
    #    module: shell
    #    cmd: make production_assets
    - name: create local temp directory
      file:
        path: '{{ temp_path }}'
        state: directory
    - name: pull current master
      git:
        repo: 'git@github.com:zsiciarz/variablestars.net.git'
        dest: '{{ project_path }}'
        clone: no
    - name: install Python requirements
      pip:
        requirements: '{{ project_path }}/requirements.txt'
        virtualenv: '{{ virtualenv_path }}'
    - name: install JS packages
      npm:
        path: '{{ project_path }}'
        production: yes
        executable: '{{ ansible_env.HOME }}/.nvm/versions/node/{{ node_version }}/bin/npm'
    - name: migrate database
      django_manage:
        command: migrate
        app_path: '{{ project_path }}'
        virtualenv: '{{ virtualenv_path }}'
    - name: copy static files
      copy:
        src: assets/build/
        dest: '{{ project_path }}/assets/build/'
    - name: collect static files
      django_manage:
        command: collectstatic
        app_path: '{{ project_path }}'
        virtualenv: '{{ virtualenv_path }}'
    - name: restart app
      shell:
        cmd: appctl restart variablestars2
